<SET RECCHN ,OUTCHAN>
<SET ZCHN ,OUTCHAN>

<NEWTYPE NULL LIST>
<SETG NULL #NULL <>>

<DEFINE SETUP-EX ()
	<FLOAD "SORT MUD">
	<FLOAD "ZILCH MUD">
	<FLOAD "MACROS MUD">
	<SETG INSERT-CRUFTY T>>

<DEFINE SAVE-IT ("OPTIONAL"
	(FILE '("PUBLIC" "SAVE" "DSK" "GUEST"))
	"AUX" (SNM ""))
	<SETUP-EX>
	<COND (<=? "SAVED" <SAVE !.FILE>>
	       "Saved.")
	      (T
	       <PRINC "ZILCH ready.">
	       <CRLF>)>>

<SAVE-IT ("Z" "SAVE" "DSK" "Z2")>
